# fly.toml app configuration file generated for connect-four on 2024-10-29T02:58:28Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'connect-four'
primary_region = 'sjc'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
